default: &default
  clients:
    default:
      database: solarsdb
      hosts:
        - localhost:27017

development:
  <<: *default

test:
  <<: *default

staging:
  <<: *default

production:
  <<: *default
