# A sample Gemfile
source "https://rubygems.org"

ruby '2.3.1'

# gem "rails"
gem "poltergeist"
gem "selenium-webdriver"
gem "nokogiri"
gem "mongo","~> 2.0"
gem "bson_ext"
gem 'mongoid', '~> 5.1.0'
gem 'activesupport'
gem 'whenever'
gem 'rake'
gem 'moji'
gem 'actionmailer'

# development
gem 'letter_opener'
